name: Build, Test, & Publish '@jalexw/calendar-ics-parser' Package

on:
  push:
    branches:
      - main

env:
  BUN_VERSION: 1.2.22

jobs:
  build-test-and-publish:
    name: "Build, test, & publish package"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.BUN_VERSION }}
      - name: Install dependencies with Bun
        run: bun install
      - name: Run package unit tests with Bun
        run: bun run test
      - name: Build package with Bun
        run: bun run build
      - name: Login to NPM registry
        run: bunx npm login --registry=https://registry.npmjs.org
        env:
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      - name: Publish package to GitHub NPM registry
        run: bun publish --access public --registry=https://registry.npmjs.org
